In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score
sb.set()

In [2]:
socnet = pd.read_csv(r'C:\Users\ASUS\Desktop\Social_Network_Ads.csv')

In [3]:
socnet.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
socnet.describe()

User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [5]:
socnet.describe(include = ['O'])

Gender
count      400
unique       2
top     Female
freq       204

In [6]:
socnet.describe(include = 'all')

User ID  Gender         Age  EstimatedSalary   Purchased
count   4.000000e+02     400  400.000000       400.000000  400.000000
unique           NaN       2         NaN              NaN         NaN
top              NaN  Female         NaN              NaN         NaN
freq             NaN     204         NaN              NaN         NaN
mean    1.569154e+07     NaN   37.655000     69742.500000    0.357500
std     7.165832e+04     NaN   10.482877     34096.960282    0.479864
min     1.556669e+07     NaN   18.000000     15000.000000    0.000000
25%     1.562676e+07     NaN   29.750000     43000.000000    0.000000
50%     1.569434e+07     NaN   37.000000     70000.000000    0.000000
75%     1.575036e+07     NaN   46.000000     88000.000000    1.000000
max     1.581524e+07     NaN   60.000000    150000.000000    1.000000

In [7]:
socnet['Gender'] = socnet['Gender'].map({'Male':1,'Female':0})

In [8]:
socnet.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510       1   19            19000          0
1  15810944       1   35            20000          0
2  15668575       0   26            43000          0
3  15603246       0   27            57000          0
4  15804002       1   19            76000          0

In [9]:
X = socnet.iloc[: ,2:]
Y = socnet.iloc[: ,4]

In [10]:
def normalise(X):
    return((X-np.min(X))/(np.max(X)-np.min(X)))


In [11]:
X.iloc[:,2:] = X.iloc[:,2:].apply(normalise)  

In [12]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.25,random_state = 0)

In [13]:
#from sklearn.linear_model import LogisticRegression
import sklearn.linear_model as lm
logreg = lm.LogisticRegression()
logreg.fit(X_train,Y_train)
pred_lr = logreg.predict(X_test)

In [14]:
cm = confusion_matrix(Y_test,pred_lr)
cm

array([[68,  0],
       [32,  0]], dtype=int64)

In [15]:
logreg.score(X_train,Y_train)

0.63

In [16]:
logreg.score(X_test,Y_test)

0.68

In [17]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=6,metric='minkowski',p=2)
knn.fit(X_train,Y_train)
pred_knn = knn.predict(X_test)
cm = confusion_matrix(Y_test,pred_knn)
cm

array([[64,  4],
       [12, 20]], dtype=int64)

In [18]:
knn.score(X_train,Y_train)

0.8533333333333334

In [19]:
knn.score(X_test,Y_test)

0.84

In [20]:
from sklearn.svm import SVC
svc = SVC(kernel = 'linear',random_state=0)
svc.fit(X_train,Y_train)
pred_svc = svc.predict(X_test)
cm = confusion_matrix(Y_test,pred_svc)
cm

array([[64,  4],
       [ 8, 24]], dtype=int64)

In [21]:
svc.score(X_train,Y_train)

0.8266666666666667

In [22]:
svc.score(X_test,Y_test)

0.88

In [23]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train,Y_train)
pred_gnb = gnb.predict(X_test)
cm = confusion_matrix(Y_test,pred_gnb)
cm

array([[67,  1],
       [ 3, 29]], dtype=int64)

In [24]:
gnb.score(X_train,Y_train)

0.93

In [25]:
gnb.score(X_test,Y_test)

0.96

In [26]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(X_train,Y_train)
pred_dtc = dtc.predict(X_test)
cm = confusion_matrix(Y_test,pred_dtc)
cm

array([[68,  0],
       [ 0, 32]], dtype=int64)

In [27]:
dtc.score(X_train,Y_train)

1.0

In [28]:
dtc.score(X_test,Y_test)

1.0

In [29]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
rfc.fit(X_train,Y_train)
pred_rfc = rfc.predict(X_test)
cm = confusion_matrix(Y_test,pred_rfc)
cm

array([[68,  0],
       [ 0, 32]], dtype=int64)

In [30]:
rfc.score(X_train,Y_train)

1.0

In [31]:
rfc.score(X_test,Y_test)

1.0